- name: Create temporary directory {{ tmp_dir }}
  file:
    path: "{{ tmp_dir }}"
    state: directory

- name: Check if golang is installed
  stat:
    path: "/usr/local/go"
  register: golang_stat

- name: Install golang1.19
  block:
    - name: Download go{{ golang_version }}.linux-amd64.tar.gz
      get_url:
        url: "https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz"
        dest: "{{ tmp_dir }}/go{{ golang_version }}.linux-amd64.tar.gz"
        checksum: "sha256:{{ golang_tar_gz_sha256 }}"

    - name: Untar golang
      unarchive:
        src: "{{ tmp_dir }}/go{{ golang_version }}.linux-amd64.tar.gz"
        dest: "/usr/local"
        remote_src: true
        owner: "root"
        group: "root"

    - name: Export golang env
      lineinfile:
        dest: "/etc/profile"
        state: present
        line: 'export PATH="/usr/local/go/bin:$PATH"'
  when: not golang_stat.stat.exists
